name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          command: npx cypress run
              
      # Upload Cypress test reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports/mochawesome

      # Generate HTML report
      - name: Generate HTML Report
        run: npx marge cypress/reports/mochawesome/*.json -f report.html -o cypress/reports/html
        working-directory: ${{ github.workspace }}
      
      # Upload HTML report
      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-html-report
          path: cypress/reports/html

